doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            user_id: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\User\UserIdType
            food_id: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\Food\FoodIdType
            meal_id: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\Meal\MealIdType
            walk_id: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\Walk\WalkIdType
            weight_measurement_id: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\WeightMeasurement\WeightMeasurementIdType
            height: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\UserIndicator\HeightType
            weight: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\Shared\WeightType
            telegram_user_id: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\User\TelegramUserIdType
            telegram_username: App\HealthTracker\Infrastructure\Doctrine\DBAL\Types\User\TelegramUsernameType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        enable_native_lazy_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            HealthTracker_Entity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/HealthTracker/Domain/Entity'
                prefix: 'App\HealthTracker\Domain\Entity'
                alias: HealthTracker_Entity
            HealthTracker_ValueObject:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/HealthTracker/Domain/ValueObject'
                prefix: 'App\HealthTracker\Domain\ValueObject'
                alias: HealthTracker_ValueObject
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
